name: "breathe_flow_dbt"
version: '1.0'
config-version: 2

profile: "breathe_flow_profile"

source-paths: ["models"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
data-paths: ["data"]
target-path: "target"
clean-targets: ["target"]

vars:
  project: "{{ env_var('GCP_PROJECT_ID', '') }}"
  dataset: "{{ env_var('BQ_DATASET', 'breathe-flow-pipeline') }}"
