steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/openaq-ingest:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/openaq-ingest:$SHORT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/openaq-ingest:$SHORT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
