FROM kestra/kestra:latest
USER root
RUN apt-get update -qq && \
    apt-get install -y python3 python3-pip --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --no-cache-dir \
    google-cloud-storage \
    google-cloud-secret-manager \
    google-auth \
    python-dotenv \
    requests
